### ISSUE TITLE
What is Server Node 1?

### ISSUE THREAD

**Issue by SoftwareRat** [r0b2g1t/k3s-cluster-on-oracle-cloud-infrastructure#12]
> `scp rancher@<SERVER_NODE_1_PUBLIC_IP>:/etc/rancher/k3s/k3s.yaml ~/.kube/config`

and what is server node 1?

> The server-nodes are at the availability domain 2 (AD-2) and the agent node are created in AD-1. 

Cannot you just say which processor arch is for the server and which one for the agent nudes?

**Comment by r0b2g1t** [comment]
The server node 1 is the first virtual machine where the controlplane is running.

The cpu architecture of the controlplane node is x64 ans for the Agent nodes arm64. If you need more information you can find it in the variables files in the compute directory.

**Comment by SoftwareRat** [comment]
> scp -i /Users/REDACTED/.ssh/REDACTED.key rancher@REDACTED:/etc/rancher/k3s/k3s.yaml ~/.kube/config
> ssh: connect to host REDACTED port 22: Operation timed out
> scp: Connection closed

Did I missed some step? @r0b2g1t

**Comment by SoftwareRat** [comment]
I had to manually allow all IP's to get access to SSH. Now I see there is no rancher user and no ~/.kube/ folder
