### ISSUE TITLE
security rules and kubectl

### ISSUE THREAD

**Issue by axlroden** [r0b2g1t/k3s-cluster-on-oracle-cloud-infrastructure#4]
Your security rules are not allowing kubectl to reach the cluster externally.

Also the public ip of the machine would need to be added to its allowed cert/listeners.

Havn't looked into how your creating the K3s but:
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--tls-san x.x.x.x" sh -s -
with x.x.x.x being the public IP would give you access.

or edit what k3s is serving directly:
kubectl -n kube-system edit secrets/k3s-serving

**Comment by r0b2g1t** [comment]
Yes, you have to setup a security rule to reach your cluster from another system by your self.

The cluster is using k3os, which has an smaller OS overhead, you have to edit the "secrets/k3s-serving" resource.
