### ISSUE TITLE
The cluster is deployed but if you try to resolve a service from another host it failed

### ISSUE THREAD

**Issue by billmetangmo** [r0b2g1t/k3s-cluster-on-oracle-cloud-infrastructure#8]
what I expect : doing nslookup from the worker node to a service should be oki but it is not

Fix:
```
sudo ufw disbale
sudo service iptables stop
sudo systemctl stop firewalld
Clear IPtables: https://github.com/k3s-io/k3s/issues/535#issuecomment-907789701
sudo netfilter-persistent save
```

**Comment by r0b2g1t** [comment]
If you want to reach non-default services you have to disable the iptables firewall.

**Comment by billmetangmo** [comment]
Yes. Would not it be good to add it on the code or at least in the documentation ( just an idea) ? Because as it is,  it's impossible to have an app with pods scheduled on 2 different nodes that works because of DNS issue.

**Comment by r0b2g1t** [comment]
Yes, I will write down some documentation.

**Comment by r0b2g1t** [comment]
I have added a solution in the user-data script:
https://github.com/r0b2g1t/k3s-cluster-on-oracle-cloud-infrastructure/blob/1835b8af4ca55e6bea1e26bc0063d33746a4e127/terraform/compute/templates/server.sh#L3
