### ISSUE TITLE
Error: Self-referential block

### ISSUE THREAD

**Issue by ItherNiT** [r0b2g1t/k3s-cluster-on-oracle-cloud-infrastructure#9]
Hi,

When I try to run TF plan command I get the following error: 

```
terraform plan -out .tfplan
var.private_key_password
  Password for private key to use for signing

  Enter a value: 

module.network.data.oci_identity_availability_domain.ad: Reading...
module.network.data.oci_identity_availability_domain.ad: Read complete after 0s [id=ocid1.availabilitydomain.oc1..xxxxxx]
╷
│ Error: Self-referential block
│ 
│   on compute/main.tf line 24, in resource "oci_core_instance" "server_0":
│   24:           server_0_ip = oci_core_instance.server_0.private_ip,
│ 
│ Configuration for oci_core_instance.server_0 may not refer to itself.
╵
╷
│ Error: Self-referential block
│ 
│   on compute/main.tf line 24, in resource "oci_core_instance" "server_0":
│   24:           server_0_ip = oci_core_instance.server_0.private_ip,
│ 
│ Configuration for oci_core_instance.server_0 may not refer to itself.
```

I had to change the `network/data.tf` `ad_number = 1` just because the region `af-johannesburg-1` doesn't allow/have `ad_number=2` 

Any idea on how I can fix this?

**Comment by r0b2g1t** [comment]
Sorry to read this I develop it for the use of two ad. I recommend to use another region.

**Comment by christian-sapconet** [comment]
I have the same issue on the UK region, that does have multiple AD's. 
I'll try and create an account on the Frankfurt region, I noticed that there are multiple references to that region in the TF files.

**Comment by ItherNiT** [comment]
Hi,

I get the same error in UK region, that does have 3-AD's. 
I'll try and create an account in the Frankfort region later today.

A separate question, but what is the nsg_id's?

**Comment by r0b2g1t** [comment]
I found the issue of the Self-referential block in the private_ip of the metadata section.

**Comment by r0b2g1t** [comment]
The nsg_id's referencing to network security groups which are allowing ssh traffic:
https://github.com/r0b2g1t/k3s-cluster-on-oracle-cloud-infrastructure/blob/787016ea76229793229fd573f45664f9f60fe4df/terraform/network/main.tf#L52
